project:
  type: website
  output-dir: docs
website:
  title: "Quarto & R Insight Hub"
  navbar:
    left:
      - text: "Analysis Results"
        href: analysis.qmd
      - text: "Personal Thought"
        href: Personal_Thought.qmd
      - text: "Lerning Reflections"
        href: references.qmd
      - text: "About me"
        href: About_me.qmd
  sidebar:
    left:
    style: "docked"
    collapse-level: 1
    search: true
    contents:
      - section: "Analysis Result"  
        contents: 
            - text: "日本歳出"
              href: Japan_Expenditure.qmd
            - text: "省庁の費用"
              href: ministry_expenses.qmd
      - section: "Personal Thought"
        contents: 
            - text: "プログラミング言語一覧" 
              href: Programming.qmd
            - text: "AI"
              href: AI.qmd
            - text: 
              href: 
      - section: "Learning Reflections"
        contents: 
            - text: "貸借対照表"
              href: BS.qmd
      - section: "About me"
        contents: 
            - text: "PCおすすめ"
              href: PC.qmd
            - text: "My book"
              href: Book.qmd
format: 
  html: 
    margin:
      bottom: 0.5in
      top: 0.5in
      left: 0.5in
      right: 0.5in
      toc: true