---
title: "Book"
editor: visual
---

### 概要

このページでは私がこれまでに読んだ本のリストを紹介しています。読書は知識を深め、新たな視点を得るための重要な手段です。私は投資、資格、プログラミング言語等の分野に関心があり、これらのテーマに関連する本を中心に読んでいます。

### 書籍一覧

#### 投資関連

-   月10万円を稼ぐ　トレード1年目の教科書

    -   著者名：高橋慶行

    -   出版年：2023年

-   買い時、売り時がひと目でわかる　株価チャート大全

    -   著者名：戸松信博

    -   出版年：2023年

-   株を買うなら最低限知っておきたい　ファンダメンタル投資の教科書　改訂版

    -   著者名：足立武志

    -   出版年：2023年 ( 第7版 )

-   暴落ドミノ　今すぐ資産はこう守れ！

    -   著者名：澤上篤人

    -   出版年：2024年

-   転換の時代を生き抜く　投資の教科書

    -   著者名：後藤達也

    -   出版年：2024年

-   わが投資術　市場は誰に微笑むか

    -   著者名：清原達郎

    -   出版年：2024年

-   会社四季報　2024年1集　新春　東洋経済

-   会社四季報　2024年2集　春号　東洋経済

-   会社四季報　2024年3集　夏号　東洋経済

#### WEB3.0 / DAO / ブロックチェーン / Defi / NFT

-   Web3とDAO　誰もが主役になれる「新しい経済」

    -   著者名：亀井聡彦、鈴木雄大、赤澤直樹

    -   出版年：2022年

-   DAO ( 分散型自律組織 )の衝撃

    -   著者名：小澤隆博

    -   出版年：2022年

#### プログラミング

-   1冊ですべて身につくHTML & CSSとWebデザイン入門講座

    -   著者名：Mana

    -   出版年：2019年

-   Rではじめるデータサイエンス

    -   著者名：Hadley Wickham , Garrett Grolemund

    -   出版年：2017年

-   改訂2版　RユーザのためのRStudio \[ 実践 \] 入門

    -   著者名：松村優哉、湯谷啓明、紀ノ定保礼、前田和寛

    -   出版年：2018年

#### 会計・資格　

-   財務諸表分析　第8版

    -   著者名：桜井久勝

    -   出版年：2020年

-   ビジネス会計検定試験公式テキスト　3級　第5版

-   ビジネス会計検定試験公式問題集　3級　第5版

-   ビジネス会計検定試験公式テキスト　2級　第5版

-   ビジネス会計検定試験公式問題集　2級　第5版

-   ビジネス会計検定試験公式テキスト　1級　第3版

-   ビジネス会計検定試験公式問題集　1級　第4版

    編者：大阪商工会議所

-   2023-2024年版　スッキリわかる　証券外務員一種

    -   監修：SAKU株式会社

    -   編者：TAC株式会社

    -   出版年：2023年

-   2023-2024年版　スッキリわかる　証券外務員二種

    -   監修：SAKU株式会社

    -   編者：TAC株式会社

    -   出版年：2023年

-   みんなが欲しかった！簿記の教科書　日商3級　商業簿記　第12版

    -   著者名：滝澤ななみ

    -   出版年：2024年

#### ビジネス

-   数値化の鬼 - 「仕事ができる人」に共通する、たった1つの思考法

    -   著者名：安藤広大

    -   出版年：2022年

-   漫画　バビロン大富豪の教え「お金」と「幸せ」を生み出す五つの法則

    -   ジョージクレイソン、坂野旭、大橋弘裕

    -   出版年：2019年
