---
title: "PC選び方"
editor: visual
author: Karuni
date: last-modified
---

#### 必要スペック

#### CPU

-   Intel Core i5 以上

-   AMD Ryzen 5　以上

    世代が古い場合、i5　Ryzen 5 ではスペックを満たせない場合も

#### メモリ

-   16GB 以上

    IDEやブラウザを同時に起動するなど、メモリを多く使用する場合が多いため16GB以上を推奨

#### ストレージ

-   SSD (256GB以上)

#### 画面サイズ

-   13インチ～15インチ

    ### PC

    ※Officeなし

    #### Dell

| Dell           | Inspiron 13  | XPS 13        | XPS13                         |
|----------------|--------------|---------------|-------------------------------|
| CPU            | Ultra 5 125H | Ultra 5 125 H | Snapdragon X Elite X1E-80-100 |
| グラフィックス | Intel Arc    | Intel Arc     | Qualcomm Adreno GPU           |
| メモリ         | 16GB         | 16GB          | 16GB                          |
| ストレージ     | 512GB        | 512GB         | 512GB                         |
| 価格           | 132,037円    | 229,980円     | 249,980円                     |

#### HP

| HP         | Pavilion Aero 13-be | Pavilion 15-eh3000 | Spectre x360 14-eu0000TU | Spectre x360 16-aa0000TU |
|------------|---------------------|--------------------|--------------------------|--------------------------|
| CPU        | Ryzen 7 7735U       | Ryzen 5 7530U      | Ultra 5 125H             | Ultra 7 155H             |
| メモリ     | 16GB                | 16GB               | 16GB                     | 16GB                     |
| ストレージ | 512GB               | 512GB              | 512GB                    | 512GB                    |
| 価格       | 125,364円           | 104,000円          | 190,918円                | 227,318円                |

#### ASUS

| ASUS           | Zenbook 14 OLED UX3405MA | Zenbook 14 OLED UX3405MA | Zenbook 14 OLED UX3405MA |
|----------------|--------------------------|--------------------------|--------------------------|
| CPU            | Core Ultra 5 125H        | Ultra 7 155H             | Ultra 9 185H             |
| グラフィックス | Intel Arc                | Intel Arc                | Intel Arc                |
| メモリ         | 16GB                     | 16GB                     | 32GB                     |
| ストレージ     | 512GB                    | 1TB                      | 1TB                      |
| 価格           | 134,800円                | 164,800円                | 199,800円                |

#### CPU

-   Intel Core Ultra 5 125H / PassMark : 21250

-   Intel Core Ultra 5 125U / PassMark : 17942

-   Intel Core Ultra 7 155H / PassMark : 24954

-   Intel Core Ultra 7 155U / PassMark : 16814

-   Intel Core Ultra 9 185H / PassMark : 28594

-   Snapdragon X Elite X1E-80-100 (不明)

-   AMD Ryzen 5 7530U / PassMark : 16211

-   AMD Ryzen 5 7535U / PassMark : 16441

-   AMD Ryzen 7 5825U / PassMark : 18385

-   AMD Ryzen 7 7730U / PassMark : 18684

-   AMD Ryzen 7 7735U / PassMark : 21340

-   AMD Ryzen 5 8640U (不明)

#### 参照

[DELL](https://www.dell.com/ja-jp) (アクセス日2024年6月1日)

[HP](https://www.hp.com/jp-ja/home.html) (アクセス日2024年6月1日)

[ASUS](https://www.asus.com/jp/) (アクセス日2024年6月1日)

[PassMark SOFTWARE](https://www.cpubenchmark.net/) (アクセス日2024年6月1日)
